version: '3'
services:
    sundbaat-client:
        container_name: sundbaat-client
        image: jvik/sundbaat-client
        restart: always
        command: ['npm', 'run', 'dev-server']
        volumes:
            - ./src:/app/src
            - ./dist/:/app/dist
            - ./.env.dev:/app/.env.dev
        tty: true
