FROM node:10.14.1

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Bundle app source
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . /app

# Wait for it
COPY wait-for-it.sh /wait-for-it.sh

EXPOSE 3000
CMD [ "npm", "start" ]